#!/usr/bin/env node

/**
 * Lightweight proto codegen placeholder.
 * - Recursively enumerates all .proto files under packages/proto-defs/protos
 * - Emits a TypeScript helper in packages/proto-defs/gen/ts/index.ts
 *   so imports like @kitchen-cpq/proto-defs resolve to the manifest.
 *
 * Replace this with real protoc/ts-proto codegen when ready.
 */

const fs = require('fs');
const path = require('path');

const repoRoot = path.join(__dirname, '..', '..');
const protoRoot = path.join(repoRoot, 'packages', 'proto-defs', 'protos');
const outDir = path.join(repoRoot, 'packages', 'proto-defs', 'gen', 'ts');

function listProtos(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...listProtos(full));
    } else if (entry.isFile() && entry.name.endsWith('.proto')) {
      files.push(full);
    }
  }
  return files;
}

const protos = listProtos(protoRoot);
if (!protos.length) {
  console.warn(`No proto files found under ${protoRoot}`);
}

fs.mkdirSync(outDir, { recursive: true });

const relativePaths = protos.map((p) => path.relative(protoRoot, p));
const outFile = path.join(outDir, 'index.ts');
const content = `// Auto-generated by tools/scripts/generate-protos.cjs\n` +
  `// Proto root: ${protoRoot}\n` +
  `export const protoRoot = ${JSON.stringify(protoRoot)} as const;\n` +
  `export const protoFiles = ${JSON.stringify(relativePaths, null, 2)} as const;\n` +
  `export type ProtoFileName = typeof protoFiles[number];\n` +
  `export const protoPathMap: Record<ProtoFileName, string> = Object.fromEntries(protoFiles.map((f) => [f, require('path').join(protoRoot, f)]));\n` +
  `export function resolveProto(name: ProtoFileName): string {\n  return protoPathMap[name];\n}\n`;

fs.writeFileSync(outFile, content, 'utf8');

console.log(`Wrote proto manifest with ${relativePaths.length} entries to ${outFile}`);
